version: '3'

services:
  bootcamp_db:
    image: mysql:latest
    container_name: bootcamp_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/app
    environment:
      MYSQL_ROOT_PASSWORD: nhan1412
      MYSQL_DATABASE: bootcamp_development
      MYSQL_USER: nhannt
      MYSQL_PASSWORD: nhan1412

  bootcamp_web:
    build: .
    container_name: bootcamp
    command: bundle exec rails s -p 5050 -b '0.0.0.0'
    volumes:
      - .:/app
      - web_rubygems:/usr/local/bundle
    ports:
      - "5050:5050"
    depends_on:
      - bootcamp_db
volumes:
  db_data:
  web_rubygems: